[package]
name = "sarek"
version = "0.1.0"
authors = ["Mike Dilger <mike@optcomp.nz>"]

[dependencies]
winit = "0.5"
image = "0.10"
libc = "0.2.21"

[dependencies.vk-sys]
git = "https://gitlab.com/dennis-hamester/vk-sys.git"
default-features = false
features = [ "vk_1_0_3", "ext_debug_report_1" ]

[target.'cfg(windows)'.dependencies]
user32-sys = "0.2"
winapi = "0.2"
